# Generated by Django 5.0.2 on 2024-05-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato',
            name='edad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dato',
            name='ficha',
            field=models.FloatField(),
        ),
    ]
